[package]
name = "omnichat"
version = "0.1.0"
authors = ["Aleksi Backman <bddubbb@gmail.com>"]

[dependencies]
libc = "0.2.0"

[[bin]]
name = "core"
path = "src/core/main.rs"

[[bin]]
name = "client"
path = "src/client/main.rs"
